blank_issues_enabled: true
contact_links:
  - name: Contributing guidelines
    url: https://github.com/cp50/ai-gateway/blob/main/CONTRIBUTING.md
    about: Read the contribution guidelines before opening an issue
